### ISSUE TITLE
Library doesn't seem to work

### ISSUE THREAD

**Issue by WaDelma** [Stebalien/gag-rs#4]
I tried to run the example that buffers stdout to temporary file in a test and it doesn't seem to capture it (I tried use `gag` for testing my interpreter):
```fish
---- interpreter::tests::example1_interprets stdout ----                                         
        Hello world!                                                                             
thread 'interpreter::tests::example1_interprets' panicked at 'assertion failed: `(left == right)`
        left: `""`,                                                                              
        right: `"Hello world!\n"`', mini-pl/src/interpreter/tests.rs:28:4                        
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                               
```

```fish
> rustc -V
rustc 1.23.0 (766bd11c8 2018-01-01)
```
and I am running Fedora 27

**Comment by Stebalien** [comment]
Could I get a copy of the code that isn't working?

**Comment by WaDelma** [comment]
I recreated the problem:

- `cargo new gag-test`
- `cargo add gag`
- copy pasted the example in docs
- wrapped it to test
- added extern

```
extern crate gag;

use std::io::Read;
use gag::BufferRedirect;

#[test]
fn test() {
    let mut buf = BufferRedirect::stdout().unwrap();
    println!("Hello world!");

    let mut output = String::new();
    buf.read_to_string(&mut output).unwrap();

    assert_eq!(&output[..], "Hello world!\n");
}
```

**Comment by WaDelma** [comment]
Any ways: I refactored my interpreter to take stdin/stdout/stderr as parameter, so I am don't have need for `gag` at the moment (I was already debating if I would use it as I would like to run the tests on windows too).

**Comment by Stebalien** [comment]
Ah... that's because rust's test framework redirects `println!` using an unstable `std::io::set_print` function. Note: It doesn't actually redirect `stdout` (file descriptor 1), it just causes all writes to `io::stdout()` to go somewhere else. Unfortunately, I can't do anything about that (in stable rust).

>  I refactored my interpreter to take stdin/stdout/stderr as parameter, so I am don't have need for gag at the moment (I was already debating if I would use it as I would like to run the tests on windows too).

That's probably for the best. The primary use-case for this library is dealing with unruly C libraries that decide to log to stdout/stderr. If you can actually control the code that's writing to stdout, the best solution is to just not write to stdout.

**Comment by Stebalien** [comment]
I've updated the documentation to reflect this. This is a really annoying and hard to figure out issue, thanks for reporting.
